version: "3"
services:
  api:
    build: .
    volumes:
      - ./:/go/src/app
    environment:
      DB_USER: "DB_USER:-app"
      DB_PASSWORD: "${DB_PASSWORD:-password}"
    ports:
      # realise dashboard
      - "5002:5002"
      # debug grpc
      - "3002:3002"
    depends_on:
      - db
  db:
    image: "mysql:8"
    restart: always
    volumes:
      - ./docker/db/init-db:/docker-entrypoint-initdb.d
      - ./db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "app"
      MYSQL_USER: "app"
      MYSQL_PASSWORD: "${DB_PASSWORD:-password}"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
  frontend:
    build: react
    volumes:
      - ./react/app:/app
  nginx:
    image: "nginx:latest"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/certs:/etc/nginx/certs
    ports:
      - "8080:80"
      - "8443:443"
    depends_on:
      - api
      - frontend
