version: 2.1

executors:
  build_golang:
    parameters:
      go-version:
        type: string
    docker:
      - image: circleci/golang:<< parameters.go-version >>
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/app/go
  build_node:
    parameters:
      node-version:
        type: string
    docker:
      - image: circleci/node:<< parameters.node-version >>
    working_directory: ~/repo

commands:
  go_mod_download:
    steps:
      - restore_cache:
          name: Restore go modules cache
          keys:
            - go-modules-{{ checksum "go.sum" }}

      - run: go mod download

      - save_cache:
          name: Save go modules cache
          key: go-modules-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

jobs:
  build_golang:
    parameters:
      go-version:
        type: string
      golangci-lint-version:
        type: string

    executor:
      name: build_golang
      go-version: << parameters.go-version >>

    steps:
      - checkout:
          path: /go/src/app

      - go_mod_download

      - run:
          name: Install GolangCI-Lint
          command: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v<< parameters.golangci-lint-version >>

      - run:
          name: Run GolangCI-Lint
          command: ./bin/golangci-lint run --tests --disable-all --enable=goimports --enable=golint --enable=govet --enable=errcheck --enable=staticcheck
      - run:
          name: Run Tests
          command: go test -race -v ./cmd/... ./pkg/...
  build_node:
    parameters:
      node-version:
        type: string

    executor:
      name: build_node
      node-version: << parameters.node-version >>

    steps:
      - checkout:
          path: ~/repo

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test

workflows:
  golang-workflow:
    jobs:
      - build_golang:
          go-version: "1.12.6"
          golangci-lint-version: "1.15.0"
  node-workflow:
    jobs:
      - build_node:
          node-version: "12.9"
